language: node_js
os: linux
cache: node_modules
dist: xenial
node_js: 12.15
jobs:
  include: 
    - stage: test
      if: branch not in (master, release)
      script: 
      - npm run lint 
    - stage: build
      if: branch in (master, release)
      script: 
      - npm run build 
